In [2]:
import numpy as np

In [5]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr = np.array(my_list)

In [9]:
type(arr)

numpy.ndarray

In [10]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[0]

1

In [12]:
arr[1] + arr[5]

8

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matrix[0]

array([1, 2, 3])

In [15]:
matrix[0, 0]

1

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[0:3]

array([1, 2, 3])

In [18]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [19]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[::3]

array([1, 4, 7])

In [21]:
arr[-3:]

array([7, 8, 9])

In [22]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [33]:
td_matrix = [
    [[1,2,3], [4,5,6], [7,8,9]], 
    [[1,2,3], [4,5,6], [7,8,9]], 
    [[1,2,3], [4,5,6], [7,8,9]]
]

In [35]:
td_matrix[0][0]

[1, 2, 3]

In [36]:
td_matrix = np.array(td_matrix)

In [37]:
td_matrix[0, 0, 0]

1

In [40]:
td_matrix[0:2, 0:2, 0:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])