In [42]:
import numpy as np

In [44]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [48]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [47]:
arr

array([1., 2., 3., 4.])

In [50]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [52]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [54]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [55]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3'], dtype='|S21')

In [57]:
arr = np.array(["0", "1", "2", "3"])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3], dtype=int8)

In [59]:
string_array = arr.astype(str)
string_array

array(['0', '1', '2', '3'], dtype='<U4')

In [60]:
string_array_to_float = string_array.astype(np.float64)
string_array_to_float

array([0., 1., 2., 3.])

In [64]:
string_array_to_int = string_array.astype(np.int64)
string_array_to_int.dtype

dtype('int64')