In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [3]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

In [7]:
tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [11]:
## Add or remove dimensions

In [14]:
tensor = np.array([1,2,3], ndmin=10)
print(tensor)
tensor.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [16]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [17]:
## Squeeze dimensions

In [21]:
print(f"tensor: {tensor}, dimension: {tensor.ndim}")
tensor_2 = np.squeeze(vector)
print(f"tensor: {tensor_2}, dimension: {tensor_2.ndim}")

tensor: [[[[[[[[[[1 2 3]]]]]]]]]], dimension: 10
tensor: [1 2 3], dimension: 1


In [22]:
array_10d = np.array([1, 2, 3], ndmin=10)
print(f"Array with 10 dimensions: {array_10d.shape}")

Array with 10 dimensions: (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)


## Challenge
### 1. Create a tensor of 5 dimensions
### 2. Add a dimension to the tensor
### 3. Remove all unecessary dimensions

In [25]:
tensor_5d = np.array([
    [
    [
        [
            [1, 0], 
            [0, 1]
        ], 
        [
            [1, 1], 
            [1, 1]
        ]
    ], 
    [
        [
            [0, 0], 
            [0, 0]
        ], 
        [
            [1, 0], 
            [0, 1]
        ]
    ]
    ]
], ndmin=5)
tensor_5d

array([[[[[1, 0],
          [0, 1]],

         [[1, 1],
          [1, 1]]],


        [[[0, 0],
          [0, 0]],

         [[1, 0],
          [0, 1]]]]])

In [26]:
tensor_5d.ndim

5

In [27]:
expanded_tensor = np.expand_dims(tensor_5d, axis=0)
print(f"Expanded tensor dimensions: {expanded_tensor.shape}")

Expanded tensor dimensions: (1, 1, 2, 2, 2, 2)


In [29]:
squeezed_tensor = np.squeeze(expanded_tensor)
print(f"Squeezed tensor dimensions: {squeezed_tensor.shape}")
print(f"No of dimensions: {squeezed_tensor.ndim}")

Squeezed tensor dimensions: (2, 2, 2, 2)
No of dimensions: 4
