In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand() # Generate a random number between 0 - 1

0.29135045221780553

In [9]:
np.random.rand(4)

array([0.26475191, 0.40827534, 0.96957384, 0.29047243])

In [10]:
np.random.rand(4,4)

array([[0.27191855, 0.65474091, 0.42723944, 0.93902782],
       [0.61528826, 0.61422555, 0.13978244, 0.2239856 ],
       [0.15669362, 0.92763308, 0.72755531, 0.11639859],
       [0.21870928, 0.51439069, 0.99421132, 0.99338517]])

In [12]:
np.random.randint(1, 15)

13

In [13]:
np.random.randint(1, 100, (10,10))

array([[78, 30, 50, 85, 77,  6, 95, 55, 13, 94],
       [52, 69, 80, 64, 51,  7,  9, 29,  7, 42],
       [66, 83, 89, 43, 82, 23, 84,  2,  7, 86],
       [ 6, 95,  2, 98, 49, 78,  2, 28, 34, 11],
       [23, 63, 10, 43, 11, 54, 96, 70, 45, 16],
       [77, 15, 35, 26, 28, 90, 17, 97, 82, 68],
       [64, 25, 28, 17, 10, 16, 78, 64, 97, 99],
       [29, 39, 92, 33, 39, 17, 99, 53, 51, 34],
       [68, 92, 76, 31, 44, 49, 21, 60, 61, 58],
       [99,  8, 81, 41, 68, 41, 65, 93,  8, 39]])