In [80]:
import numpy as np

In [81]:
arr = np.random.randint(1, 10, (3,2))
arr

array([[5, 8],
       [2, 7],
       [4, 9]])

In [82]:
arr.shape

(3, 2)

In [83]:
arr.reshape(1,6)

array([[5, 8, 2, 7, 4, 9]])

In [84]:
arr.reshape(2,3)

array([[5, 8, 2],
       [7, 4, 9]])

In [85]:
np.reshape(arr, (1,6))

array([[5, 8, 2, 7, 4, 9]])

In [86]:
arr

array([[5, 8],
       [2, 7],
       [4, 9]])

In [87]:
np.reshape(arr, (2,3), "C")  # Using C programming language

array([[5, 8, 2],
       [7, 4, 9]])

In [88]:
np.reshape(arr, (2,3), "F")  # Using Fortran programming language

array([[5, 4, 7],
       [2, 8, 9]])

In [89]:
np.reshape(arr, (2,3), "A")  # Using the storage optimization in my system

array([[5, 8, 2],
       [7, 4, 9]])

## Create an array and change its dimensions
### Attempt to change the array in a way that does not respect the original structure

In [90]:
my_arr = np.random.randint(0,10, (3, 3))
my_arr

array([[1, 3, 3],
       [7, 5, 9],
       [3, 9, 5]])

In [91]:
my_arr.reshape(1,9)

array([[1, 3, 3, 7, 5, 9, 3, 9, 5]])

In [92]:
my_arr.reshape(9,1)

array([[1],
       [3],
       [3],
       [7],
       [5],
       [9],
       [3],
       [9],
       [5]])

In [93]:
my_arr.reshape(10,1)

ValueError: cannot reshape array of size 9 into shape (10,1)

## Exercises: Understanding Shapes

##### 1. Create a 1D array with elements from 1 to 10. Print its shape.

In [ ]:
array_1d = np.random.randint(1,10, (10))
print(array_1d)
array_1d.ndim

##### 2. Create a 2D array of shape (5, 2) with elements from 11 to 20. 

In [ ]:
array_2d = np.random.randint(11,20, (5,2))
print(array_2d)
array_2d.ndim

##### 3. Create a 3D array of shape (2, 3, 4) with random integers between 1 to 50. Print its shape.

In [ ]:
array_3d = np.random.randint(1, 50, (2,3,4))
print(array_3d)
array_3d.ndim

## Exercises: Basic Reshaping

##### 1. Reshape the 1D array you created in Exercise 1 to have a shape (5, 2). Print the new array.

In [ ]:
array_1d.reshape(5,2)

##### 2. Reshape the 2D array you created in Exercise 1 to be a 1D array. Print the new array.

In [ ]:
array_2d_to_1d = array_2d.reshape(10)
print(array_2d_to_1d)
print(array_2d_to_1d.ndim)

## Exercises: Advanced Reshaping

##### 1. Convert the 2D array you created in Exercise 1 into a column vector. Print the new array and its shape.

In [ ]:
column_vector = array_2d.reshape(10,1)
print(column_vector)
print("Dimension: ", column_vector.ndim)

##### 2. Reshape the 3D array you created in Exercise 1 to a shape (4, 3, 2). Print the new array.

In [ ]:
reshaped_array = array_3d.reshape(4,3,2)
print(reshaped_array)
print("Dimension: ", reshaped_array.ndim)

## Exercise 4: Using -1 in Reshape

##### 1. Use -1 to reshape the 1D array you created in Exercise 1 into a column vector. Print the new array.

In [ ]:
new_column_vector = array_1d.reshape(-1, 1)
print(new_column_vector)
print("Dimension: ", new_column_vector.ndim)

##### 2. Use -1 to reshape the 3D array you created in Exercise 1 to have 12 elements in each sub-array. Print the new array.

In [ ]:
new_array_3d = array_3d.reshape(2, 3, -1)
print(array_3d)

## Exercise 5: Challenge

##### 1. Create a 4D array of shape (3, 2, 2, 4) with random integers between 1 to 100. Print its shape.

In [ ]:
array_4d = np.random.randint(1, 100, (3, 2, 2, 4))
print(array_4d)
print("Dimension: ", array_4d.ndim)

##### 2. Reshape this 4D array into a 2D array of shape (12, 4). Print the new array.

In [ ]:
array_4d_to_2d = array_4d.reshape(12,4)
print(array_4d_to_2d)
print("Dimension: ", array_4d_to_2d.ndim)