In [1]:
import numpy as np

In [7]:
arr = np.random.randint(1, 10, (3,2))
arr

array([[7, 2],
       [8, 1],
       [4, 6]])

In [5]:
arr.shape

(3, 2)

In [8]:
arr.reshape(1,6)

array([[7, 2, 8, 1, 4, 6]])

In [10]:
arr.reshape(2,3)

array([[7, 2, 8],
       [1, 4, 6]])

In [11]:
np.reshape(arr, (1,6))

array([[7, 2, 8, 1, 4, 6]])

In [14]:
arr

array([[7, 2],
       [8, 1],
       [4, 6]])

In [12]:
np.reshape(arr, (2,3), "C")  # Using C programming language

array([[7, 2, 8],
       [1, 4, 6]])

In [13]:
np.reshape(arr, (2,3), "F")  # Using Fortran programming language

array([[7, 4, 1],
       [8, 2, 6]])

In [15]:
np.reshape(arr, (2,3), "A")  # Using the storage optimization in my system

array([[7, 2, 8],
       [1, 4, 6]])

## Create an array and change its dimensions
### Attempt to change the array in a way that does not respect the original structure

In [21]:
my_arr = np.random.randint(0,10, (3, 3))
my_arr

array([[0, 6, 7],
       [1, 6, 5],
       [2, 5, 2]])

In [23]:
my_arr.reshape(1,9)

array([[0, 6, 7, 1, 6, 5, 2, 5, 2]])

In [24]:
my_arr.reshape(9,1)

array([[0],
       [6],
       [7],
       [1],
       [6],
       [5],
       [2],
       [5],
       [2]])

In [25]:
my_arr.reshape(10,1)

ValueError: cannot reshape array of size 9 into shape (10,1)

## Exercises: Understanding Shapes

##### 1. Create a 1D array with elements from 1 to 10. Print its shape.

In [48]:
array_1d = np.random.randint(1,10, (10))
print(array_1d)
array_1d.ndim

[8 8 1 1 2 5 8 1 1 8]


1

##### 2. Create a 2D array of shape (5, 2) with elements from 11 to 20. 

In [44]:
array_2d = np.random.randint(11,20, (5,2))
print(array_2d)
array_2d.ndim

[[11 17]
 [12 17]
 [19 13]
 [18 19]
 [19 13]]


2

##### 3. Create a 3D array of shape (2, 3, 4) with random integers between 1 to 50. Print its shape.

In [46]:
array_3d = np.random.randint(1, 50, (2,3,4))
print(array_3d)
array_3d.ndim

[[[12 35 36 43]
  [ 1 46  5 43]
  [29  7 13 25]]

 [[38 11 40 17]
  [ 3 44 45 21]
  [29 34 29 18]]]


3

## Exercises: Basic Reshaping

##### 1. Reshape the 1D array you created in Exercise 1 to have a shape (5, 2). Print the new array.

In [49]:
array_1d.reshape(5,2)

array([[8, 8],
       [1, 1],
       [2, 5],
       [8, 1],
       [1, 8]])

##### 2. Reshape the 2D array you created in Exercise 1 to be a 1D array. Print the new array.

In [57]:
array_2d_to_1d = array_2d.reshape(10)
print(array_2d_to_1d)
print(array_2d_to_1d.ndim)

[11 17 12 17 19 13 18 19 19 13]
1


## Exercises: Advanced Reshaping

##### 1. Convert the 2D array you created in Exercise 1 into a column vector. Print the new array and its shape.

In [60]:
column_vector = array_2d.reshape(10,1)
print(column_vector)
print("Dimension: ", column_vector.ndim)

[[11]
 [17]
 [12]
 [17]
 [19]
 [13]
 [18]
 [19]
 [19]
 [13]]
Dimension:  2


##### 2. Reshape the 3D array you created in Exercise 1 to a shape (4, 3, 2). Print the new array.

In [61]:
reshaped_array = array_3d.reshape(4,3,2)
print(reshaped_array)
print("Dimension: ", reshaped_array.ndim)

[[[12 35]
  [36 43]
  [ 1 46]]

 [[ 5 43]
  [29  7]
  [13 25]]

 [[38 11]
  [40 17]
  [ 3 44]]

 [[45 21]
  [29 34]
  [29 18]]]
Dimension:  3


## Exercise 4: Using -1 in Reshape

##### 1. Use -1 to reshape the 1D array you created in Exercise 1 into a column vector. Print the new array.

In [79]:
new_column_vector = array_1d.reshape(-1, 1)
print(new_column_vector)
print("Dimension: ", new_column_vector.ndim)

[[8]
 [8]
 [1]
 [1]
 [2]
 [5]
 [8]
 [1]
 [1]
 [8]]
Dimension:  2


##### 2. Use -1 to reshape the 3D array you created in Exercise 1 to have 12 elements in each sub-array. Print the new array.

In [72]:
new_array_3d = array_3d.reshape(2, 3, -1)
print(array_3d)

[[[11 30  3  8]
  [18 31 16 19]
  [25 38 40 34]]

 [[30 42 19 35]
  [ 6 26  2  4]
  [ 5 17 28 41]]]


## Exercise 5: Challenge

##### 1. Create a 4D array of shape (3, 2, 2, 4) with random integers between 1 to 100. Print its shape.

In [75]:
array_4d = np.random.randint(1, 100, (3, 2, 2, 4))
print(array_4d)
print("Dimension: ", array_4d.ndim)

[[[[13 62 43 69]
   [10 91 22 72]]

  [[78  7 29 92]
   [35 89 85 78]]]


 [[[46 40 38  5]
   [39 34 70 86]]

  [[28 74 68 61]
   [54 82 13 32]]]


 [[[22 69 76 39]
   [52 92 20 12]]

  [[68 17  6 25]
   [ 3 52 19 27]]]]
Dimension:  4


##### 2. Reshape this 4D array into a 2D array of shape (12, 4). Print the new array.

In [78]:
array_4d_to_2d = array_4d.reshape(12,4)
print(array_4d_to_2d)
print("Dimension: ", array_4d_to_2d.ndim)

[[13 62 43 69]
 [10 91 22 72]
 [78  7 29 92]
 [35 89 85 78]
 [46 40 38  5]
 [39 34 70 86]
 [28 74 68 61]
 [54 82 13 32]
 [22 69 76 39]
 [52 92 20 12]
 [68 17  6 25]
 [ 3 52 19 27]]
Dimension:  2
