# Main functions of Numpy

In [83]:
import numpy as np

vector = np.random.randint(1,20, 10)
vector

array([ 6, 18,  3,  2,  5,  2, 10,  1, 13, 10])

In [84]:
matrix = vector.reshape(2, 5)
matrix

array([[ 6, 18,  3,  2,  5],
       [ 2, 10,  1, 13, 10]])

### Max number in an array

In [85]:
vector.max()

18

In [86]:
print(matrix)
matrix.max(0)  # The max number by column

[[ 6 18  3  2  5]
 [ 2 10  1 13 10]]


array([ 6, 18,  3, 13, 10])

In [87]:
print("vector: ", vector)
vector.argmax()  # The position where our max value is

vector:  [ 6 18  3  2  5  2 10  1 13 10]


1

In [88]:
print("matrix: ", matrix)
matrix.argmax(0)  # finding the indices of the max value along axis 0 (the column-wise axis)

matrix:  [[ 6 18  3  2  5]
 [ 2 10  1 13 10]]


array([0, 0, 0, 1, 1])

### Minimum number in an array

In [89]:
print(vector)
print("minimum value: ", vector.min())
print("The min value position: ", vector.argmin())

[ 6 18  3  2  5  2 10  1 13 10]
minimum value:  1
The min value position:  7


In [90]:
print(matrix)
print("minimum value: ", matrix.min(0)) # finding the indices of the min value along axis 0 (the column-wise axis)
print("The min value position: ", matrix.argmin(0))

[[ 6 18  3  2  5]
 [ 2 10  1 13 10]]
minimum value:  [ 2 10  1  2  5]
The min value position:  [1 1 1 0 0]


### The difference between the maximum value minus the minimum value

In [91]:
print(vector)
print("peak to peak value (max - min): ", vector.ptp())

[ 6 18  3  2  5  2 10  1 13 10]
peak to peak value (max - min):  17


In [92]:
print(matrix)
print("max - min of each column", matrix.ptp(0))

[[ 6 18  3  2  5]
 [ 2 10  1 13 10]]
max - min of each column [ 4  8  2 11  5]


### Percentile

In [93]:
vector.sort()
print(vector)
print("Percentile 50: ", np.percentile(vector, 50))
print("median: ", np.median(vector))

[ 1  2  2  3  5  6 10 10 13 18]
Percentile 50:  5.5
median:  5.5


In [94]:
print(matrix)
print("Percentile 50: ", np.percentile(matrix, 50))

[[ 1  2  2  3  5]
 [ 6 10 10 13 18]]
Percentile 50:  5.5


In [95]:
print(matrix)
print("median by column", np.median(matrix, 0))

[[ 1  2  2  3  5]
 [ 6 10 10 13 18]]
median by column [ 3.5  6.   6.   8.  11.5]


### Standard deviation, Variance, Mean

In [96]:
print(vector)
np.std(vector)  # Standard Deviation ** 2 =  Variance

[ 1  2  2  3  5  6 10 10 13 18]


5.310367218940701

In [97]:
print("Variance: ", np.var(vector))

Variance:  28.2


In [98]:
print("Mean: ", np.mean(vector))

Mean:  7.0


### Concatenate

In [105]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

print("a: ", a)
print("b: ", b)

a:  [[1 2]
 [3 4]]
b:  [5 6]


In [106]:
print(f"a dimensions: {a.ndim} \nb dimensions: {b.ndim}")

a dimensions: 2 
b dimensions: 1


In [107]:
reshaped_b = b.reshape(1,2)

In [108]:
np.concatenate((a, reshaped_b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
b = np.expand_dims(b, axis=0)
print(a)
print(b)
print(b.T)
np.concatenate((a, b.T), axis=1)

[[1 2]
 [3 4]]
[[5 6]]
[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])