# Copy

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr_slide = arr[0:6]
arr_slide

array([0, 1, 2, 3, 4, 5])

In [6]:
arr_slide[:] = 0
arr_slide

array([0, 0, 0, 0, 0, 0])

In [8]:
arr_copy = arr.copy()
print(arr_copy)
arr_copy
print()

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])