# Conditions

In [24]:
import numpy as np

In [25]:
arr = np.linspace(1, 10, 10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [26]:
indices = arr > 5
indices

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [27]:
arr[indices]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [28]:
arr[(arr > 5) & (arr < 9)]  # It olny return values greater 5 but less than 9 

array([6, 7, 8], dtype=int8)

In [29]:
arr[arr > 5] = 99  # Set all values in the 'arr' array that are greater than 5 to 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [30]:
arr[arr==99]  # Show all values equal to 99

array([99, 99, 99, 99, 99], dtype=int8)