In [31]:
import numpy as np

In [32]:
my_list = [1, 2]
my_list

[1, 2]

In [33]:
my_list * 2

[1, 2, 1, 2]

In [34]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
copied_arr = arr.copy()
copied_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Operations

In [36]:
print(copied_arr)
print(copied_arr * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [37]:
print(copied_arr)
print(copied_arr + 2)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11]


In [38]:
1 / arr

/var/folders/wd/jk044m6n4071_2qs36xrjw340000gn/T/ipykernel_70649/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [39]:
print(copied_arr)
print(copied_arr ** 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [40]:
print("copied_array: ", copied_arr)
print("arr: ", arr)
print("arr + copied_array: ", arr + copied_arr)

copied_array:  [0 1 2 3 4 5 6 7 8 9]
arr:  [0 1 2 3 4 5 6 7 8 9]
arr + copied_array:  [ 0  2  4  6  8 10 12 14 16 18]


In [41]:
print("copied_array: ", copied_arr)
print("arr: ", arr)
print("arr + copied_array: ", arr - copied_arr)

copied_array:  [0 1 2 3 4 5 6 7 8 9]
arr:  [0 1 2 3 4 5 6 7 8 9]
arr + copied_array:  [0 0 0 0 0 0 0 0 0 0]


In [42]:
print("copied_array: ", copied_arr)
print("arr: ", arr)
print("arr + copied_array: ", arr * copied_arr)

copied_array:  [0 1 2 3 4 5 6 7 8 9]
arr:  [0 1 2 3 4 5 6 7 8 9]
arr + copied_array:  [ 0  1  4  9 16 25 36 49 64 81]


In [43]:
matrix = arr.reshape(2, 5)
matrix_2 = matrix.copy()

print("matrix:\n", matrix)
print("matrix_2:\n", matrix_2)
print("matrix - matrix_2:\n", matrix - matrix_2)

matrix:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
matrix_2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
matrix - matrix_2:
 [[0 0 0 0 0]
 [0 0 0 0 0]]


In [44]:
matrix_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [45]:
np.matmul(matrix, matrix_2.T)

array([[ 30,  80],
       [ 80, 255]])

In [46]:
matrix @ matrix_2.T

array([[ 30,  80],
       [ 80, 255]])